# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal

# Cria os diretorios abaixo, para serem usados apos a execucao do Container
RUN mkdir -p /dotnet6core
RUN mkdir -p /db-tmc

# Define o diretorio de trabalho/home do Container
WORKDIR /dotnet6core

# Inicia a publicacao do App na porta 3000
# ENTRYPOINT ["dotnet" "MatchControl.API.dll"]
ENTRYPOINT ["/usr/bin/sh", "-c", "dotnet MatchControl.API.dll", "&& /bin/bash"]