name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    
    - name: Define a variavel DATETIME
      run: echo "DATETIME=`date +"%Y%m%d-%H%M"`" >> $GITHUB_ENV

    - name: Exibe o valor de DATETIME
      run: echo ${{ env.DATETIME }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: vicente7/tmc
        tags: tmc_reactjs:${{ env.DATETIME }}
        # addTimestamp: true
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
