name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

    - name: Define a variavel DATETIME, ajustado para o Timezone do Brasil
      run: echo "DATETIME=$`date +"%Y-%m-%d_%H-%M-%S" -d '-3 hours'`" >> $GITHUB_ENV

    - name: Exibe o valor de DATETIME
      run: echo ${{ env.DATETIME }}

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-ReactNative
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: vicente7/tmc
        tags: reactjs_${{ env.DATETIME }}
        registry: docker.io
        dockerfile: Dockerfile-ReactNative
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
